### PR TITLE
[result] fix subtest referencing objects

### LINKED ISSUE #219: subtest with object breaks XML generation
When a subtest references an object, it breaks the XML generation at this point: https://github.com/xmlrunner/unittest-xml-reporting/blob/e8a337c2597a4124f290feb28b2eeb3991c93567/xmlrunner/result.py#L520

### PR DESCRIPTION
**Pull request by XonqNopp**
Close #219

### CODE REVIEW

**Comment by danielfm** [comment]
# [Codecov](https://codecov.io/gh/xmlrunner/unittest-xml-reporting/pull/220?src=pr&el=h1) Report
> Merging [#220](https://codecov.io/gh/xmlrunner/unittest-xml-reporting/pull/220?src=pr&el=desc) into [master](https://codecov.io/gh/xmlrunner/unittest-xml-reporting/commit/e8a337c2597a4124f290feb28b2eeb3991c93567&el=desc) will **increase** coverage by `5.05%`.
> The diff coverage is `100.00%`.

[Impacted file tree graph](https://codecov.io/gh/xmlrunner/unittest-xml-reporting/pull/220?src=pr&el=tree)

```diff
@@            Coverage Diff             @@
##           master     #220      +/-   ##
==========================================
+ Coverage   94.48%   99.54%   +5.05%     
==========================================
  Files          15       15              
  Lines        1523     1525       +2     
==========================================
+ Hits         1439     1518      +79     
+ Misses         84        7      -77     
```


| [Impacted Files](https://codecov.io/gh/xmlrunner/unittest-xml-reporting/pull/220?src=pr&el=tree) | Coverage Δ | |
|---|---|---|
| [xmlrunner/result.py](https://codecov.io/gh/xmlrunner/unittest-xml-reporting/pull/220/diff?src=pr&el=tree#diff-eG1scnVubmVyL3Jlc3VsdC5weQ==) | `98.59% <100.00%> (+0.85%)` | :arrow_up: |
| [tests/django\_example/app/tests.py](https://codecov.io/gh/xmlrunner/unittest-xml-reporting/pull/220/diff?src=pr&el=tree#diff-dGVzdHMvZGphbmdvX2V4YW1wbGUvYXBwL3Rlc3RzLnB5) | `100.00% <0.00%> (ø)` | |
| [tests/django\_example/app2/tests.py](https://codecov.io/gh/xmlrunner/unittest-xml-reporting/pull/220/diff?src=pr&el=tree#diff-dGVzdHMvZGphbmdvX2V4YW1wbGUvYXBwMi90ZXN0cy5weQ==) | `100.00% <0.00%> (ø)` | |
| [xmlrunner/extra/djangotestrunner.py](https://codecov.io/gh/xmlrunner/unittest-xml-reporting/pull/220/diff?src=pr&el=tree#diff-eG1scnVubmVyL2V4dHJhL2RqYW5nb3Rlc3RydW5uZXIucHk=) | `96.77% <0.00%> (ø)` | |
| [tests/django\_test.py](https://codecov.io/gh/xmlrunner/unittest-xml-reporting/pull/220/diff?src=pr&el=tree#diff-dGVzdHMvZGphbmdvX3Rlc3QucHk=) | `100.00% <0.00%> (+74.00%)` | :arrow_up: |

------

[Continue to review full report at Codecov](https://codecov.io/gh/xmlrunner/unittest-xml-reporting/pull/220?src=pr&el=continue).
> **Legend** - [Click here to learn more](https://docs.codecov.io/docs/codecov-delta)
> `Δ = absolute <relative> (impact)`, `ø = not affected`, `? = missing data`
> Powered by [Codecov](https://codecov.io/gh/xmlrunner/unittest-xml-reporting/pull/220?src=pr&el=footer). Last update [e8a337c...ed4666c](https://codecov.io/gh/xmlrunner/unittest-xml-reporting/pull/220?src=pr&el=lastupdated). Read the [comment docs](https://docs.codecov.io/docs/pull-request-comments).

**Comment by XonqNopp** [comment]
Actually it should also fix when there are floats in the subtest

**Comment by XonqNopp** [comment]
@dnozay did I do something wrong?

**Comment by dnozay** [comment]
@XonqNopp - it would be good to have a unit test that demonstrates / exercises the incorrect behavior.

**Comment by XonqNopp** [comment]
I added tests and tried them: before the fix, the build failed https://travis-ci.org/github/xmlrunner/unittest-xml-reporting/builds/676106789

With the fix it is now passing https://travis-ci.org/github/xmlrunner/unittest-xml-reporting/builds/676107976

However, the pytest step failed. And I must admit that I cannot understand what is wrong after reading the log for 15min. Can you please give me a hint as to what I should fix?

**Comment by XonqNopp** [comment]
@dnozay any help to understand how to fix the test would be appreciated ;-)

**Comment by dnozay** [comment]
```
__________________ TestCaseSubclassWithNoSuper.test_something __________________
cls = <class '_pytest.runner.CallInfo'>
func = <function call_runtest_hook.<locals>.<lambda> at 0x7f208078a550>
when = 'call'
reraise = (<class '_pytest.outcomes.Exit'>, <class 'KeyboardInterrupt'>)
    @classmethod
    def from_call(cls, func, when, reraise=None) -> "CallInfo":
        #: context of invocation: one of "setup", "call",
        #: "teardown", "memocollect"
        start = time()
        excinfo = None
        try:
>           result = func()
.tox/pytest/lib/python3.8/site-packages/_pytest/runner.py:244: 
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 
.tox/pytest/lib/python3.8/site-packages/_pytest/runner.py:217: in <lambda>
    lambda: ihook(item=item, **kwds), when=when, reraise=reraise
.tox/pytest/lib/python3.8/site-packages/pluggy/hooks.py:286: in __call__
    return self._hookexec(self, self.get_hookimpls(), kwargs)
.tox/pytest/lib/python3.8/site-packages/pluggy/manager.py:93: in _hookexec
    return self._inner_hookexec(hook, methods, kwargs)
.tox/pytest/lib/python3.8/site-packages/pluggy/manager.py:84: in <lambda>
    self._inner_hookexec = lambda hook, methods, kwargs: hook.multicall(
.tox/pytest/lib/python3.8/site-packages/_pytest/runner.py:143: in pytest_runtest_call
    raise e
.tox/pytest/lib/python3.8/site-packages/_pytest/runner.py:135: in pytest_runtest_call
    item.runtest()
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 
self = <TestCaseFunction test_something>
    def runtest(self):
        # TODO: move testcase reporter into separate class, this shouldnt be on item
        import unittest
    
>       testMethod = getattr(self._testcase, self._testcase._testMethodName)
E       AttributeError: 'TestCaseSubclassWithNoSuper' object has no attribute '_testMethodName'
.tox/pytest/lib/python3.8/site-packages/_pytest/unittest.py:210: AttributeError
```

I think this is an issue on `pytest` for not practicing defensive coding.
https://github.com/pytest-dev/pytest/blob/92767fec5122a14fbf671374c9162e947278339b/src/_pytest/unittest.py#L206-L210

this seems similar to https://github.com/xmlrunner/unittest-xml-reporting/issues/189

**Comment by dnozay** [comment]
https://github.com/python/cpython/blob/3.8/Lib/unittest/case.py#L375-L407
```
     If it is necessary to override the __init__ method, the base class
    __init__ method must always be called. It is important that subclasses
    should not change the signature of their __init__ method, since instances
    of the classes are instantiated automatically by parts of the framework
    in order to be run.
```

gonna have to remove the broken test `TestCaseSubclassWithNoSuper`

**Comment by dnozay** [comment]
@XonqNopp - can you please rebase and try again? I'll merge if CI passes.

**Comment by XonqNopp** [comment]
@dnozay all tests passed :-)

**Pull request merged**
