### PR TITLE
Generate classname from test data

### PR DESCRIPTION
**Pull request by gliptak**
Allows for doctest names (intending to keep backward compatibility)

### CODE REVIEW

**Comment by gliptak** [comment]
```landscape-bot``` didn't trigger for ```a633966```

**Comment by gliptak** [comment]
@dnozay Did you have a chance to review? Thanks

**Comment by dnozay** [comment]
The `needs_testcase` label means that this pull request does not have any tests to verify behavior. Could you please add some tests to make sure there are no regressions? Thank you.

**Comment by gliptak** [comment]
@dnozay Would you like to see other changes? Thanks

**Comment by gliptak** [comment]
@dnozay Have you decided on a date to release 1.13.1 or 1.14.0? Thanks
https://github.com/apache/spark/pull/9710

**Pull request merged**
