### PR TITLE
fix for issue #79

### PR DESCRIPTION
**Pull request by cmodien**
fix for issue #79

### CODE REVIEW

**Comment by cmodien** [comment]
The change you proposed worked for me in Jython.

**Comment by dnozay** [comment]
still fails on python 3...

https://docs.python.org/3/library/stdtypes.html#textseq

> Changed in version 3.3: For backwards compatibility with the Python 2 series, the u prefix is once again permitted on string literals. It has no effect on the meaning of string literals and cannot be combined with the r prefix.

**Comment by dnozay** [comment]
any chance `u'[\u0000-\u0008\u000B\u000C\u000E-\u001F\uD800-\uDFFF\uFFFE\uFFFF]'` works for you?

**Comment by cmodien** [comment]
It doesn't... I get the same UnicodeDecodeError.
Jython is using Java's string impl which is utf-16. 
I found a thread that talks about something similar. http://sourceforge.net/p/jython/mailman/message/31340733/
I'm not sure how to do a .encode("UTF-8") though.

**Pull request closed without merging**
